name: collection_walker
description: Walk large firestore collections with ease
version: 1.0.2
homepage: https://github.com/ArcaneArts/collection_walker
environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  fast_log: '>=1.0.0 <2.0.0'
  synchronized: '>=3.0.1 <4.0.0'
  cloud_firestore: '>=4.0.0 <5.0.0'
dev_dependencies:
  flutter_lints: ^2.0.1
